services:
  php-apache:
    build: . 
    ports: 
      - "8000:80"
    volumes: 
      - ./services-web:/var/www/html
    depends_on:
      - mysql 
    networks:
      - app-network 
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestock_bdd
      MYSQL_USER: gestock_user
      MYSQL_PASSWORD: N7!qV4@xT9#pL2zK
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_gestock
    links:
      - mysql
    environment:
      PMA_HOST: mysql        
      PMA_PORT: 3306
      ARBITRARY_SETTINGS: 1     
    ports:
      - "8080:80"         
    networks:
      - app-network


volumes:
  mysql-data:
networks:
  app-network: